FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY --chown=node:node . .
RUN chown -R node:node /app

EXPOSE 5173

USER node

CMD ["npm", "run", "dev"]
