FROM golang:1.25-alpine3.22 AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git build-base

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=1 GOOS=linux go build -o todo-app .

# Final stage
FROM alpine:3.22

WORKDIR /app

# Install runtime deps
RUN apk add --no-cache wget ca-certificates

# Copy binary from builder
COPY --from=builder /app/todo-app .

EXPOSE 8080

CMD ["./todo-app"]
