name: Gather File Evidences

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  ci-test-evidences:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Setup go-ctrf-json-reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      
      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: |
          go test -v -coverprofile=coverage.out -json ./... | go-ctrf-json-reporter --verbose -output ctrf-report.json
      
      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "Coverage is below 95%"
            exit 1
          fi
      - name: Upload CTRF to CCF
        if: always()
        uses: compliance-framework/agent-action@v0.0.1
        with:
          # simple test for the sake of testing :)
          api_url: https://examinational-unmeasured-mathilda.ngrok-free.dev 
          plugins: |
              files_todo_app_ctrf:
                config:
                  file_path: /github/workspace//github/workspace/ctrf-report.json
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-ctrf-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework

  ci-lint-evidences:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m --output.sarif.path out_sarif.json
      
      - name: upload sarif to CCF
        if: always()
        uses: compliance-framework/agent-action@v0.0.1
        with:
          # simple test for the sake of testing :)
          api_url: https://examinational-unmeasured-mathilda.ngrok-free.dev
          plugins: |
            # Upload SARIF report
            files_todo_app_golangcilint_sarif:
              config:
                file_path: /github/workspace/"/github/workspace/out_sarif.json"
              source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
              policies:
                - ghcr.io/compliance-framework/plugin-file-attestation-sarif-policies:v0.1.0
              labels:
                tier: vcs
                team: containersolutions
            # Attest golangci-lint configuration
            files_todo_app_golangcilint_config:
              config:
                file_path: /github/workspace/"/github/workspace/.golangci.yml"
                attestation_path: /github/workspace/"/github/workspace/.sigstore/.golangci.yml.bundle"
                authorized_signers: "gustavo.carvalho@container-solutions.com"
              source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
              policies:
                - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
              labels:
                tier: vcs
                team: containersolutions
                repository: todo-app
                organization: compliance-framework

  gather-file-evidences:
    name: Gather File Evidences
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: upload file attestation evidences to CCF
        uses: compliance-framework/agent-action@v0.0.1
        with:
          # simple test for the sake of testing :)
          api_url: https://examinational-unmeasured-mathilda.ngrok-free.dev 
          plugins: |
              files_todo_app_security:
                config:
                  file_path: /github/workspace/SECURITY.md
                  attestation_path: /github/workspace/.sigstore/SECURITY.md.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework
              files_todo_app_configuration:
                config:
                  file_path: /github/workspace/CONFIGURATION.md
                  attestation_path: /github/workspace/.sigstore/CONFIGURATION.md.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
              files_todo_app_test_trace:
                config:
                  file_path: /github/workspace/TEST_REQUIREMENT_TRACE.md
                  attestation_path: /github/workspace/.sigstore/TEST_REQUIREMENT_TRACE.md.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
              files_todo_app_plan:
                config:
                  file_path: /github/workspace/PLAN.md
                  attestation_path: /github/workspace/.sigstore/PLAN.md.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework
              files_todo_app_evidence_workflow:
                config:
                  file_path: /github/workspace/.github/workflows/evidences.yml
                  attestation_path: /github/workspace/.sigstore/.github/workflows/evidences.yml.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework
              files_todo_app_evidence_ci:
                config:
                  file_path: /github/workspace/.github/workflows/ci.yml
                  attestation_path: /github/workspace/.sigstore/.github/workflows/ci.yml.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework
              files_todo_app_evidence_test_traceability_workflow:
                config:
                  file_path: /github/workspace/.github/workflows/test-traceability.yml
                  attestation_path: /github/workspace/.sigstore/.github/workflows/test-traceability.yml.bundle
                  authorized_signers: "gustavo.carvalho@container-solutions.com"
                source: ghcr.io/compliance-framework/plugin-file-attestation:v0.1.0
                policies:
                  - ghcr.io/compliance-framework/plugin-file-attestation-policies:v0.1.0
                labels:
                  tier: vcs
                  team: containersolutions
                  repository: todo-app
                  organization: compliance-framework